// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/27/2024, 12:11:52 PM
const configMerger = require("C:/Users/Ali/Desktop/task/task/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Ali/Desktop/task/task/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/plugins/**/*.{js,ts,mjs}","C:/Users/Ali/Desktop/task/task/composables/**/*.{js,ts,mjs}","C:/Users/Ali/Desktop/task/task/utils/**/*.{js,ts,mjs}","C:/Users/Ali/Desktop/task/task/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali/Desktop/task/task/app.config.{js,ts,mjs}"] }));

module.exports = config
